### ISSUE TITLE
pod install 安装报错

### ISSUE THREAD

**Issue by twlk-jzy** [changsanjiang/SJVideoPlayer#606]
**必现/偶发?**
必现/偶发

JSON::ParserError - 416: unexpected token at '{
      "name": "AsyncLoad",
      "source_files": "SJUIKit/AsyncLoad/*.{h,m}",
      "dependencies": {
        "SJUIKit/CornerMask'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:748:in `from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:722:in `from_file'

**Comment by lhyl** [comment]
解决了吗

**Comment by xyhuangjia** [comment]
> 解决了吗

重装cocoapods 试试
